                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
			                           loadstring(game:HttpGet(('https://luascrip.github.io/luascriptsroblox/Prevail-X-main.lua'),true))() -- // the script \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
                                      -- // Prevail X \\ --
                                 -- // created by: 02hacks \\ --
